export const VIZAG_LOCATIONS = [
  'Bheemunipatnam Phase 1',
  'Bheemunipatnam Phase 2',
  'Bheemunipatnam Phase 3',
  'Kommadi Layout',
  'Kommadi Extension',
  'Pendurthi Layout',
  'Anakapalle Extension',
  'Anakapalle New Town',
  'MVP Colony',
  'Madhurawada',
  'Rushikonda',
  'Gopalapatnam',
  'Seethammadhara',
  'Other',
] as const

export const SIZE_TILES = [
  '100 sq yards',
  '150 sq yards',
  '200 sq yards',
  '240 sq yards',
  '267 sq yards',
  '300 sq yards',
  '333 sq yards',
  '400 sq yards',
  '500 sq yards',
  '600 sq yards',
  '800 sq yards',
  '1000 sq yards',
  '1200 sq yards',
  '1500 sq yards',
  '2000 sq yards',
  '2400 sq yards',
  '3000 sq yards',
  '4000 sq yards',
  '5000 sq yards',
  'Custom',
] as const

export const PRICE_TILES = [
  { label: '10 Lakhs', lakhs: 10 },
  { label: '15 Lakhs', lakhs: 15 },
  { label: '20 Lakhs', lakhs: 20 },
  { label: '25 Lakhs', lakhs: 25 },
  { label: '30 Lakhs', lakhs: 30 },
  { label: '35 Lakhs', lakhs: 35 },
  { label: '40 Lakhs', lakhs: 40 },
  { label: '45 Lakhs', lakhs: 45 },
  { label: '50 Lakhs', lakhs: 50 },
  { label: '55 Lakhs', lakhs: 55 },
  { label: '60 Lakhs', lakhs: 60 },
  { label: '65 Lakhs', lakhs: 65 },
  { label: '70 Lakhs', lakhs: 70 },
  { label: '75 Lakhs', lakhs: 75 },
  { label: '80 Lakhs', lakhs: 80 },
  { label: '90 Lakhs', lakhs: 90 },
  { label: '1 Cr', lakhs: 100 },
  { label: '1.25 Cr', lakhs: 125 },
  { label: '1.35 Cr', lakhs: 135 },
  { label: '1.5 Cr', lakhs: 150 },
  { label: '2 Cr', lakhs: 200 },
] as const

export type VizagLocation = (typeof VIZAG_LOCATIONS)[number]
export type SizeTile = (typeof SIZE_TILES)[number]
export type PriceTile = (typeof PRICE_TILES)[number]
